### ISSUE TITLE
How to use your 'ext:configuration_object' with 'ext:form'?

### ISSUE THREAD

**Issue by typo3ua** [romm/configuration_object#27]
I came across your extension for TYPO3 CMS it is very interesting and useful.
I would like to use him with "ext:form".
But I do not know how to use your 'ext:configuration_object' with 'ext:form'?
I need your help.
I want create the form (ext:form) with two fields "username" and "email" and I need to check or the email already exists in the database. If not, then to allow to adds the record in the database.(FE_USER) If yes then  not to allow to adds the record in the database.(FE_USER) 
![email_valid](https://user-images.githubusercontent.com/638022/43210280-536f19ea-9037-11e8-9a73-f79adb938a99.png)

**Comment by romm** [comment]
Hi, I think you misunderstood the usage that can be done with this extension. In no way it will help you with the need you described.

You should probably take a look at the official documentation of EXT:form at https://docs.typo3.org/typo3cms/extensions/form/
